main/default/objects/Purchase_History__c/Purchase_History__c.object-meta.xml
<CustomObject>
    <description>To Store the Order details</description>
    <label>Purchase History</label>
    <nameField>
        <displayFormat>Order-{0000}</displayFormat>
        <label>Purchase History</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Purchase_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Links the Purchase History to an account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Histories</relationshipLabel>
    <relationshipName>Purchase_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Purchase_History__c/fields/List_Of_Products__c.field-meta.xml
<CustomField>
    <fullName>List_Of_Products__c</fullName>
    <description>To store the list of Products</description>
    <label>List Of Products</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Purchase_History__c/fields/Loyalty_Points_Used__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Points_Used__c</fullName>
    <description>This Field Stores the Loyalty Points Used for that particular Purchase</description>
    <inlineHelpText>Loyalty Points Used for that particular Purchase</inlineHelpText>
    <label>Loyalty Points Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Purchase_History__c/fields/Order_Amount__c.field-meta.xml
<CustomField>
    <fullName>Order_Amount__c</fullName>
    <description>It stores the Order Amount</description>
    <label>Order Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Purchase_History__c/fields/Redeem_Points__c.field-meta.xml
<CustomField>
    <fullName>Redeem_Points__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox Option for Customer To Redeem the Loyalty Points</description>
    <label>Redeem Points</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/allPurchurseHistory.cls
public class allPurchurseHistory {
 public Account accObj {get; set;}
 public DateTime currentDateTime{get; set;} 
 public List<Purchase_History__c>  purchaseList {get; set;}
     public allPurchurseHistory(ApexPages.standardController accCont){
        Id accId = accCont.getId();
        
        this.accObj = [SELECT Id,Name,BillingStreet,BillingCity,BillingState,BillingCountry,BillingPostalCode,PersonEmail,Business_Email__c,Type_of_Customer__c,LastModifiedById FROM Account where Id =:accId];
        this.currentDateTime = System.now();
        this.purchaseList =[Select Id,Name,List_Of_Products__c,Order_Amount__c,Loyalty_Points_Used__c,Redeem_Points__c,Total_Amount__c from Purchase_History__c where Account__c =:accId];
        
        }
}