main/default/objects/Purchase_History__c/Purchase_History__c.object-meta.xml
<CustomObject>
    <description>To Store the Order details</description>
    <label>Purchase History</label>
    <nameField>
        <displayFormat>Order-{0000}</displayFormat>
        <label>Purchase History</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Purchase_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Links the Purchase History to an account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Histories</relationshipLabel>
    <relationshipName>Purchase_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Purchase_History__c/fields/List_Of_Products__c.field-meta.xml
<CustomField>
    <fullName>List_Of_Products__c</fullName>
    <description>To store the list of Products</description>
    <label>List Of Products</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Purchase_History__c/fields/Order_Amount__c.field-meta.xml
<CustomField>
    <fullName>Order_Amount__c</fullName>
    <description>It stores the Order Amount</description>
    <label>Order Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Purchase_History__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Upi</fullName>
            </value>
            <value>
                <fullName>Paypal</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Purchase_History__c/fields/Redeem_Points__c.field-meta.xml
<CustomField>
    <fullName>Redeem_Points__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox Option for Customer To Redeem the Loyalty Points</description>
    <label>Redeem Points</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/PurchaseHistoryHandlerTest.cls
@isTest
public class PurchaseHistoryHandlerTest {

    @isTest
    static void testEngagementScoreUpdate() {
        // Insert Accounts
        Account acc1 = new Account(Name = 'Account 1',recordTypeId='012gK0000008wZtQAI', Business_Email__c='vijaya.sirisha5@gmail.com',Engagement_Score__c = 10);
       // Account acc2 = new Account(Name = 'Account 2');
        list<Account> a=new list<Account>();
        a.add(acc1);
        //a.add(acc2);
        insert a;
 
        // Insert Purchase History records
        List<Purchase_History__c> purchases = new List<Purchase_History__c>{
            //new Purchase_History__c(Account__c = acc1.Id, Redeem_Points__c = true),  // +7
            new Purchase_History__c(Account__c = acc1.Id,List_Of_Products__c='Dress',Payment_Method__c='Cash',Order_Amount__c=5000,Redeem_Points__c = false) // +5
            //new Purchase_History__c(Account__c = acc2.Id, Redeem_Points__c = false)  // +5
        };

        Test.startTest();
        insert purchases;
        Test.stopTest();

        // Verify updated Engagement Scores
        Account updatedAcc1 = [SELECT Engagement_Score__c FROM Account WHERE Id = :acc1.Id];
        //Account updatedAcc2 = [SELECT Engagement_Score__c FROM Account WHERE Id = :acc2.Id];

        System.assertEquals(13, updatedAcc1.Engagement_Score__c, 'Acc1 Score should be 15');
        //System.assertEquals(5, updatedAcc2.Engagement_Score__c, 'Acc2 Score should be 5');
    }
}