main/default/objects/Engagement_Activity__c/Engagement_Activity__c.object-meta.xml
<CustomObject>
    <label>Engagement Activity</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Engagement Activity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Engagement_Activity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3)</booleanFilter>
        <filterItems>
            <field>$Source.Target_Audience__c</field>
            <operation>equals</operation>
            <valueField>Account.Customer_Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Target_Audience__c</field>
            <operation>equals</operation>
            <value>All Customers</value>
        </filterItems>
        <filterItems>
            <field>Account.Customer_Segment__c</field>
            <operation>equals</operation>
            <value>New Customers, Existing Customers, VIP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagement Activities</relationshipLabel>
    <relationshipName>Engagement_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Engagement_Activity__c/fields/Engagement_Score__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Score__c</fullName>
    <description>This field stores the engagement score</description>
    <label>Engagement Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/classes/engagementActivityHandler.cls
public class engagementActivityHandler
{
    public static void updateEngagementScore(List<Engagement_Activity__c> newRecords) 
    {
        Set<Id> accIdSet = new Set<Id>();    
        for (Engagement_Activity__c engagementactrec : newRecords)
        {
            if (engagementactrec.Account__c != null) 
            {
                accIdSet.add(engagementactrec.Account__c);
            }
        }
        List<Account> accList = [Select Id,Engagement_Score__c from Account where Id IN: accIdSet];
        List<Account> accountsToUpdate = new List<Account>();
        if(!accList.isEmpty())
        {
            for(Account accLists : accList)
            {
                Decimal engagementscore = accLists.Engagement_Score__c != null ? accLists.Engagement_Score__c : 0;
                accLists.Engagement_Score__c = engagementscore + 2; 
                accountsToUpdate.add(accLists);
            }
            
            if (!accountsToUpdate.isEmpty())
            {
                update accountsToUpdate;
            }
        }
    }
}