main/default/objects/Engagement_Activity__c/Engagement_Activity__c.object-meta.xml
<CustomObject>
    <label>Engagement Activity</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Engagement Activity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Engagement_Activity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3)</booleanFilter>
        <filterItems>
            <field>$Source.Target_Audience__c</field>
            <operation>equals</operation>
            <valueField>Account.Customer_Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Target_Audience__c</field>
            <operation>equals</operation>
            <value>All Customers</value>
        </filterItems>
        <filterItems>
            <field>Account.Customer_Segment__c</field>
            <operation>equals</operation>
            <value>New Customers, Existing Customers, VIP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagement Activities</relationshipLabel>
    <relationshipName>Engagement_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Engagement_Activity__c/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loyalty Program</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Loyalty_Program__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Loyalty_Program__c</referenceTo>
    <relationshipLabel>Engagement Activities</relationshipLabel>
    <relationshipName>Engagement_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Engagement_Activity__c/fields/Medium__c.field-meta.xml
<CustomField>
    <fullName>Medium__c</fullName>
    <label>Medium</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>In-App Notification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Loyalty_Program__c/Loyalty_Program__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program</label>
    <nameField>
        <displayFormat>LP-{0000}</displayFormat>
        <label>Loyalty Program ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Loyalty_Program__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loyalty Programs</relationshipLabel>
    <relationshipName>Loyalty_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Loyalty_Program__c/fields/Loyalty_Points_Earned__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Points_Earned__c</fullName>
    <label>Loyalty Points Earned</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Loyalty_Program__c/fields/Points_Balance__c.field-meta.xml
<CustomField>
    <fullName>Points_Balance__c</fullName>
    <formula>if(text(Program_Status__c)=&apos;Expired&apos;,0,Loyalty_Points_Earned__c - Points_Used__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Points Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Loyalty_Program__c/fields/Points_Used__c.field-meta.xml
<CustomField>
    <fullName>Points_Used__c</fullName>
    <label>Points Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Loyalty_Program__c/fields/Program_Status__c.field-meta.xml
<CustomField>
    <fullName>Program_Status__c</fullName>
    <label>Program Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Purchase_History__c/Purchase_History__c.object-meta.xml
<CustomObject>
    <description>To Store the Order details</description>
    <label>Purchase History</label>
    <nameField>
        <displayFormat>Order-{0000}</displayFormat>
        <label>Purchase History</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Purchase_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Links the Purchase History to an account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Histories</relationshipLabel>
    <relationshipName>Purchase_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Purchase_History__c/fields/Engagement_Activity__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement Activity</label>
    <referenceTo>Engagement_Activity__c</referenceTo>
    <relationshipLabel>Purchase Histories</relationshipLabel>
    <relationshipName>Purchase_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Purchase_History__c/fields/List_Of_Products__c.field-meta.xml
<CustomField>
    <fullName>List_Of_Products__c</fullName>
    <description>To store the list of Products</description>
    <label>List Of Products</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Purchase_History__c/fields/Loyalty_Points_Earned__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Points_Earned__c</fullName>
    <formula>Order_Amount__c  / 100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loyalty Points Earned</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Purchase_History__c/fields/Loyalty_Points_Used__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Points_Used__c</fullName>
    <description>This Field Stores the Loyalty Points Used for that particular Purchase</description>
    <inlineHelpText>Loyalty Points Used for that particular Purchase</inlineHelpText>
    <label>Loyalty Points Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Purchase_History__c/fields/Order_Amount__c.field-meta.xml
<CustomField>
    <fullName>Order_Amount__c</fullName>
    <description>It stores the Order Amount</description>
    <label>Order Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

main/default/classes/CustomerInteractionTracking.cls
public class CustomerInteractionTracking {
    @AuraEnabled
    public static list<Purchase_History__c> getPurchaseList(id accid){
        list<Purchase_History__c> purchList=[SELECT Name,List_Of_Products__c, Total_Items__c, Order_Amount__c, Loyalty_Points_Earned__c, Total_Amount__c, Loyalty_Points_Used__c, CreatedDate FROM Purchase_History__c where Account__c=:accid order by CreatedDate Desc limit 3];
     return purchList;
    }
    
    @AuraEnabled
    public static list<Engagement_Activity__c> getEngList(id accid){
        list<Engagement_Activity__c> engList=[SELECT Name,Medium__c,CreatedDate FROM Engagement_Activity__c where Account__c=:accid order by CreatedDate Desc limit 3];
     return engList;
    }
    
    @AuraEnabled
    public static list<Loyalty_Program__c> getLoyaltyList(id accid){
        list<Loyalty_Program__c> loyaltyList=[SELECT Name,Loyalty_Points_Earned__c,	Points_Balance__c,Points_Used__c,Program_Status__c,Expiry_Date__c FROM Loyalty_Program__c where Account__c=:accid order by CreatedDate Desc limit 3];
     return loyaltyList;
    }

}