main/default/objects/Engagement_Activity__c/Engagement_Activity__c.object-meta.xml
<CustomObject>
    <label>Engagement Activity</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Engagement Activity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Engagement_Activity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3)</booleanFilter>
        <filterItems>
            <field>$Source.Target_Audience__c</field>
            <operation>equals</operation>
            <valueField>Account.Customer_Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Target_Audience__c</field>
            <operation>equals</operation>
            <value>All Customers</value>
        </filterItems>
        <filterItems>
            <field>Account.Customer_Segment__c</field>
            <operation>equals</operation>
            <value>New Customers, Existing Customers, VIP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagement Activities</relationshipLabel>
    <relationshipName>Engagement_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Engagement_Activity__c/fields/Engagement_Notes__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Notes__c</fullName>
    <label>Engagement Notes</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Engagement_Activity__c/fields/Engagement_Score__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Score__c</fullName>
    <description>This field stores the engagement score</description>
    <label>Engagement Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Engagement_Activity__c/fields/Medium__c.field-meta.xml
<CustomField>
    <fullName>Medium__c</fullName>
    <label>Medium</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>In-App Notification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Engagement_Activity__c/fields/Target_Audience__c.field-meta.xml
<CustomField>
    <fullName>Target_Audience__c</fullName>
    <label>Target Audience</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Customers</fullName>
            </value>
            <value>
                <fullName>Existing Customers</fullName>
            </value>
            <value>
                <fullName>VIP</fullName>
            </value>
            <value>
                <fullName>All Customers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Purchase_History__c/Purchase_History__c.object-meta.xml
<CustomObject>
    <description>To Store the Order details</description>
    <label>Purchase History</label>
    <nameField>
        <displayFormat>Order-{0000}</displayFormat>
        <label>Purchase History</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Purchase_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Links the Purchase History to an account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Histories</relationshipLabel>
    <relationshipName>Purchase_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Purchase_History__c/fields/Engagement_Activity__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement Activity</label>
    <referenceTo>Engagement_Activity__c</referenceTo>
    <relationshipLabel>Purchase Histories</relationshipLabel>
    <relationshipName>Purchase_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Purchase_History__c/fields/Redeem_Points__c.field-meta.xml
<CustomField>
    <fullName>Redeem_Points__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox Option for Customer To Redeem the Loyalty Points</description>
    <label>Redeem Points</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/EngagementActivityTest.cls
@isTest
public class EngagementActivityTest {

    @isTest
    static void testEngagementScoreUpdate() {
        // Insert Accounts
        Account acc1 = new Account(Name = 'Account 1',recordTypeId='012gK0000008wZtQAI', Business_Email__c='vijaya.sirisha5@gmail.com',Engagement_Score__c = 10,Customer_Segment__c ='Existing Customers');
       // Account acc2 = new Account(Name = 'Account 2');
        list<Account> a=new list<Account>();
        a.add(acc1);
        //a.add(acc2);
        insert a;
 
        // Insert Purchase History records
        List<Engagement_Activity__c> engagementactrec = new List<Engagement_Activity__c>{
            //new Purchase_History__c(Account__c = acc1.Id, Redeem_Points__c = true),  // +7
            new Engagement_Activity__c(Account__c = acc1.Id,Target_Audience__c ='Existing Customers',Medium__c ='Email',Engagement_Notes__c ='abc') // +5
            //new Purchase_History__c(Account__c = acc2.Id, Redeem_Points__c = false)  // +5
        };

        Test.startTest();
        insert engagementactrec;
        Test.stopTest();

        // Verify updated Engagement Scores
        Account updatedAcc1 = [SELECT Engagement_Score__c FROM Account WHERE Id = :acc1.Id];
        System.debug('updatedAcc1'+updatedAcc1.Engagement_Score__c);
        //Account updatedAcc2 = [SELECT Engagement_Score__c FROM Account WHERE Id = :acc2.Id];

        System.assertEquals(12, updatedAcc1.Engagement_Score__c, 'Acc1 Score should be 15');
        //System.assertEquals(5, updatedAcc2.Engagement_Score__c, 'Acc2 Score should be 5');
    }
}